USE [master]
GO

/****** Object:  Database [teste]    Script Date: 10/10/2019 17:04:28 ******/
CREATE DATABASE [teste]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'teste', FILENAME = N'D:\SQLDevice\MSSQL11.MSSQLSERVER\MSSQL\DATA\teste.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'teste_log', FILENAME = N'D:\SQLDevice\MSSQL11.MSSQLSERVER\MSSQL\DATA\teste_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO

ALTER DATABASE [teste] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [teste].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [teste] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [teste] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [teste] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [teste] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [teste] SET ARITHABORT OFF 
GO

ALTER DATABASE [teste] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [teste] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [teste] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [teste] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [teste] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [teste] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [teste] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [teste] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [teste] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [teste] SET  DISABLE_BROKER 
GO

ALTER DATABASE [teste] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [teste] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [teste] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [teste] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [teste] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [teste] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [teste] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [teste] SET RECOVERY FULL 
GO

ALTER DATABASE [teste] SET  MULTI_USER 
GO

ALTER DATABASE [teste] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [teste] SET DB_CHAINING OFF 
GO

ALTER DATABASE [teste] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [teste] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [teste] SET  READ_WRITE 
GO

